/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.trabalhooo.viewInterfacesGraficas;

import com.google.gson.Gson;
import com.mycompany.ArquivosDeDados.Arquivo;
import com.mycompany.trabalhooo.Departamento;
import com.mycompany.trabalhooo.Disciplina;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enedilson
 */


public class TelaDepartamentoDados extends javax.swing.JFrame {

     public List<Disciplina> disciplinas;
     public List<Departamento> departamentos;
     public Arquivo arq;
    /**
     * Creates new form TelaDepartamentoDados
     */

    public TelaDepartamentoDados(List<Disciplina> disc, List<Departamento> dep) {
        initComponents();
        this.disciplinas = disc;
        this.departamentos = dep;
        this.arq = new Arquivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //Recebe os Dados das Disciplinas da TelaDisciplinaDados
    public void adicionaDepartamento() {
        Departamento dep = new Departamento();
        dep.addDisciplina(buscaDisciplina(jtfDisciplina1.getText()));
        dep.addDisciplina(buscaDisciplina(jtfDisciplina2.getText()));
        dep.setNome(jtfNomeDepto.getText());
        
        Gson gson = new Gson();
        String toJsonDepartamento  = gson.toJson(departamentos);
                System.out.println("toJson = " + toJsonDepartamento);
                if(arq.Write(Constantes.ARQUIVO_DEPARTAMENTO, toJsonDepartamento)){    
                    System.out.println("Texto salvo");
                }
                else{
                    System.out.println("Erro!");
                }
    }
    
    private Disciplina buscaDisciplina(String d) {
        //try{
        int i = 0;
        while(i < disciplinas.size()){
            if(disciplinas.get(i).getNome().equals(d)){
                return disciplinas.get(i);
            }
            i++;  
        }
        //throw new Exception();
        //}catch(Exception a){
        //    JOptionPane.showMessageDialog(null,"Erro no preenchimento dos dados");
        //}
        JOptionPane.showMessageDialog(null, "Disciplina nao encontrada");
        return null;
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeDepto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDisciplina1 = new javax.swing.JTextField();
        jtfDisciplina2 = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome");

        jtfNomeDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeDeptoActionPerformed(evt);
            }
        });

        jLabel3.setText("Disciplinas");

        jtfDisciplina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDisciplina1ActionPerformed(evt);
            }
        });

        jtfDisciplina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDisciplina2ActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbVoltar)
                        .addGap(48, 48, 48)
                        .addComponent(jbAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeDepto)
                            .addComponent(jtfDisciplina1)
                            .addComponent(jtfDisciplina2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jtfDisciplina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jtfDisciplina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVoltar)
                    .addComponent(jbAdicionar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDisciplina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDisciplina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDisciplina1ActionPerformed

    private void jtfDisciplina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDisciplina2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDisciplina2ActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
         //try {
             // TODO add your handling code here:
             adicionaDepartamento();
             JOptionPane.showMessageDialog(null, "Departamento Criado!");
             jtfDisciplina1.setText("");
             jtfDisciplina2.setText("");
             jtfNomeDepto.setText("");
         //} catch (Exception ex) {
         //    JOptionPane.showMessageDialog(null,"Falha no cadastro");
         //}
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jtfNomeDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeDeptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamentoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamentoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamentoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDepartamentoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaDepartamentoDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JTextField jtfDisciplina1;
    private javax.swing.JTextField jtfDisciplina2;
    private javax.swing.JTextField jtfNomeDepto;
    // End of variables declaration//GEN-END:variables
}
